Blog/urls.py
from django.contrib import admin
from django.urls import path
from django.conf.urls import url, include

from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('admin/', admin.site.urls),
    url(r"", include("Documents.urls")),
    url(r"", include("Comments.urls"))
]

static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

Comments/urls.py
#!/usr/bin/env python
# -*- coding: utf-8 -*-

"""
    Desc:

"""

from django.conf.urls import url

from . import views

app_name = 'Comments'
urlpatterns = [
    url(r'^comment/post/(?P<post_pk>[0-9]+)/$', views.post_comment, name='post_comment'),
]

Documents/urls.py
#!/usr/bin/env python
# -*- coding: utf-8 -*-

"""
    Desc:

"""


from django.conf.urls import url
from . import views

app_name = "Documents"

urlpatterns = [
    url(r"^$", views.index, name="index"),
    url(r"^post/(?P<pk>[0-9]+)/$", views.detail, name="detail")
]

Comments/models.py
from django.db import models
from django import forms


class Comment(models.Model):
    name = models.CharField(max_length=100)
    email = models.EmailField(max_length=255)
    url = models.URLField(blank=True)
    text = models.TextField()
    created_time = models.DateTimeField(auto_now_add=True)

    post = models.ForeignKey('Documents.Post', on_delete=False)

    def __str__(self):
        return self.text[:20]

Documents/models.py
from django.db import models
from django.contrib.auth.models import User
from django.urls import reverse


class Category(models.Model):

    category_name = models.CharField(max_length=100)

    def __str__(self):
        return self.category_name


class Tag(models.Model):

    tag_name = models.CharField(max_length=70)

    def __str__(self):
        return self.tag_name


class Post(models.Model):

    title = models.CharField(max_length=100)

    body = models.TextField()

    create_date = models.DateTimeField(auto_now=True)

    modified_date = models.DateTimeField(auto_now=True)

    excerpt = models.CharField(max_length=200, blank=True)

    category = models.ForeignKey(Category, on_delete=True)

    tags = models.ManyToManyField(Tag, blank=True)

    author = models.ForeignKey(User, on_delete=True)

    def get_absolute_url(self):

        # reverse 函数，它的第一个参数的值是 'Documents:detail'，意思是 Documents 应用下的 name=detail 的函数
        return reverse('Documents:detail', kwargs={'pk': self.pk})

    def __str__(self):
        return self.title

Comments/forms.py
#!/usr/bin/env python
# -*- coding: utf-8 -*-

"""
    Desc:

"""

from django import forms
from .models import Comment


class CommentForm(forms.ModelForm):

    class Meta:
        model = Comment
        fields = ["name", "email", "url", "text"]

        widgets = {
            "name": forms.TextInput(attrs={"class": "form-control", "placeholder": "昵称", "type": "nickname"}),
            "email": forms.EmailInput(attrs={"class": "form-control", "placeholder": "电子邮件", "type": "email"})
        }

Comments/views.py
from django.shortcuts import render, get_object_or_404, redirect
from Documents.models import Post

from .forms import CommentForm


def post_comment(request, post_pk):

    post = get_object_or_404(Post, pk=post_pk)

    if request.method == "POST":
        form = CommentForm(request.POST)

        if form.is_valid():

            comment = form.save(commit=False)
            comment.post = post

            comment.save()

            return redirect(post)

        else:
            comment_list = post.comment_set.all()
            context = {'post': post,
                       'form': form,
                       'comment_list': comment_list
                       }
            return render(request, 'Documents/detail.html', context=context)

    return redirect(post)

Documents/views.py
import markdown
from django.utils.html import strip_tags
from django.shortcuts import render, get_object_or_404
from .models import Post
from Comments.forms import CommentForm
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger

BLOG_NAME = "Note."


def index(request):

    post_list = Post.objects.all().order_by("-create_date")

    for post in post_list:
        md = markdown.Markdown(extensions=[
            'markdown.extensions.extra',
            'markdown.extensions.codehilite',
        ])
        post.excerpt = strip_tags(md.convert(post.body))[:54]

    paginator = Paginator(post_list, 5)
    page = request.GET.get('page')

    try:
        page_items = paginator.page(page)
    except PageNotAnInteger:
        # 如果用户请求的页码号不是整数，显示第一页
        page_items = paginator.page(1)
    except EmptyPage:
        # 如果用户请求的页码号超过了最大页码号，显示最后一页
        page_items = paginator.page(paginator.num_pages)

    return render(
        request,
        "Documents/index.html",
        context={"title": BLOG_NAME,
                 # "post_list": post_list,
                 "post_list": page_items}
    )


def detail(request, pk):
    post = get_object_or_404(Post, pk=pk)

    post.body = markdown.markdown(
        post.body,
        extensions=[
            'markdown.extensions.extra',
            'markdown.extensions.codehilite',
            'markdown.extensions.toc',
        ]
    )

    form = CommentForm()
    comment_list = post.comment_set.all()

    return render(
        request,
        "Documents/detail.html",
        context={"title": BLOG_NAME,
                 "post": post,
                 "form": form,
                 "comment_list": comment_list}
    )

templates/Documents/base.html
{% load static %}

<!doctype html>
<html lang="en">
<head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link href="https://cdn.bootcss.com/twitter-bootstrap/3.3.7/css/bootstrap.min.css" rel="stylesheet">
    <link rel="stylesheet" href="{% static 'Documents/css/github.css' %}">
    <link rel="stylesheet" href="{% static 'Documents/css/extra.css' %}">
    <title>{% block post-title %}{% endblock post-title %}{{ title }}</title>
</head>

<body>

<div class="jumbotron">
    <h1 class="blog-name"><a href="{% url 'Documents:index' %}">{{ title }}</a></h1>
</div>

<div class="container">
    {% block content %}{% endblock content %}
</div>

<footer class="blog-footer">
    <div class="container">
        <p><b>岁月无婷无华</b></p>
        <p class="blog-record">京ICP备19005249号 | <a rel="license" href="http://creativecommons.org/licenses/by-nc-sa/3.0/"><img alt="知识共享许可协议" style="border-width:0" src="https://i.creativecommons.org/l/by-nc-sa/3.0/80x15.png" /></a></p>
    </div>
</footer>

<!-- Optional JavaScript -->
<!-- jQuery first, then Popper.js, then Bootstrap JS -->
<script src="https://cdn.bootcss.com/twitter-bootstrap/3.3.7/js/bootstrap.min.js"></script>
<script src="https://cdn.bootcss.com/jquery/3.2.1/jquery.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>

</body>
</html>

templates/Documents/detail.html
{% extends 'Documents/base.html' %}

{% block post-title %}{{ post.title }} - {% endblock post-title %}

{% block content %}

    <div class="item">
        <div class="article-title">
            <h3>{{ post.title }}</h3>
        </div>

        <div class="article-info">
            {{ post.category }} / {{ post.create_date }}
        </div>

        <div class="article-body">
            {{ post.body | safe}}
        </div>

        <div class="article-footer">
            最后修改时间：{{ post.modified_date }}
        </div>
    </div>

    <hr>

    <h5>发表评论</h5>
    <br />
    <form action="{% url 'Comments:post_comment' post.pk %}" method="post" class="comment-form">
        {% csrf_token %}
        <div class="row">
            <div class="col-md-6">
                {{ form.name }}
            </div>
            <div class="col-md-6">
                {{ form.email }}
            </div>
            <div class="col-md-12">
                <textarea placeholder="评论" name="text" class="form-control" rows="4" required></textarea>
                <button type="submit" class="btn btn-default">发表</button>
            </div>
        </div>
    </form>
    <br />

    <ul class="comment-list list-unstyled">
        {% if comment_list %}
            <h5>评论列表</h5>
        {% endif %}

        {% for comment in comment_list %}
            <li class="comment-item">
                <span class="nickname">{{ comment.name }} | </span>
                <time class="comment-submit-date">{{ comment.created_time }}</time>
                <div class="text">
                    {{ comment.text }}
                </div>
            </li>
            <br/>
        {% endfor %}
    </ul>


{% endblock content %}

templates/Documents/index.html
{% extends 'Documents/base.html' %}

{% block content %}
    <div class="list-group">
        {% for post in post_list %}
            <div class="item">
                <div class="article-title index-title">
                    <h3><a class="underline" href="{{ post.get_absolute_url }}">{{ post.title }}</a></h3>
                </div>
                <div class="article-excerpt">
                    <p>{{ post.excerpt}}...</p>
                    <a href="{{ post.get_absolute_url }}" class="more-link">继续阅读 <span class="meta-nav">→</span></a>
                </div>
            </div>
        {% empty %}
            <div class="no-article">暂时还没有发布的文章！</div>
        {% endfor %}

        {% if post_list %}
            <!-- 分页开始 -->
            <div class="pagination-item">
                <ul class="pagination">
                    <li><a href="?page=1">首页</a></li>
                    {% if post_list.has_previous %}
                        <li><a href="?page={{ post_list.previous_page_number }}">上一页</a></li>
                    {% endif %}

                    {% for num in post_list.paginator.page_range %}
                        <li>
                            <a href="?page={{ num }}">
                                {{ num }}
                            </a>
                        </li>
                    {% endfor %}

                    {% if post_list.has_next %}
                        <li><a href="?page={{ post_list.next_page_number }}">下一页</a></li>
                    {% endif %}
                    <li><a href="?page={{ post_list.paginator.num_pages }}">尾页</a></li>
                </ul>
            </div>
            <!-- 分页结束 -->
        {% endif %}
    </div>

{% endblock content %}